# for new env update
# IMAGE_TAG
# client_websocket_base
# client_websocket_port
# client_run_mode
# environment_name
# slack notification endpoint
on:
  pull_request:
    branches:
      - dev
    types: [closed] 

name: Staging Deploy to Amazon ECR & Deploy to Beanstalk

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Fail if not merged
        if: ${{ !github.event.pull_request.merged }}
        run: |
          exit 1

      - name: Fail if not synced with base branch
        run: |
          # This verifies that there is only one file changed between base and this branch,
          # that the file is our version file, and that only one line has changed.
          # If these criteria are not met, the action fails here and no pr is made.
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
          git diff --numstat --no-color ${{ GITHUB_SHA }}~1 ${{ GITHUB_SHA }} -- | xargs
          [ '1 1 .github/staging-version' = "`git diff --numstat --no-color ${{ github.base_ref }} HEAD -- | xargs`" ]

      - name: Success step
        if: ${{ success() }}
        run: |
          echo 'Woo!'

