# for new env update
# IMAGE_TAG
# client_websocket_base
# client_websocket_port
# client_run_mode
# environment_name
# slack notification endpoint
on:
  release:
    types:
      - published
    tags:
      - release-*

name: Staging Deploy to Amazon ECR & Deploy to Beanstalk

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: 2

      - name: Fail if not merged
        if: ${{ !github.event.pull_request.merged }}
        run: |
          exit 1

      - name: Fail if not synced with base branch
        run: |
          # This verifies that there is only one file changed in the merge commit,
          # that the file is our version file, and that only one line has changed.
          # If these criteria are not met, the action fails here and no pr is made.
          git diff --numstat --no-color HEAD^ -- | xargs
          # [ '1 1 .github/staging-version' = "`git diff --numstat --no-color ${{ github.event.pull_request.merge_commit_sha }}~1 ${{ github.event.pull_request.merge_commit_sha }} -- | xargs`" ]
          [ '1 1 .github/staging-version' = "`git diff --numstat --no-color HEAD^ -- | xargs`" ]

      - name: Success step
        if: ${{ success() }}
        run: |
          echo 'Woo!'

