on:
  push:
    tags:
      # Run this for all tags starting with v. E.g. v2.4.1
      - v*

name: Update version file and create PR

jobs:
  version-pr:
    name: Make version update PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev 
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Checkout tag
        uses: actions/checkout@v2

      # - name: Create branch from tag
      #   run: |
      #     git checkout -b ${{ github.ref }}-staging-version-update 

      - name: Update version file
        run: |
          ./.github/scripts/update-version-file.sh ${{ github.ref }}

      - name: Commit version file
        run: |
          git add .github/staging-version
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git commit -m "Automatically updated version file to ${{ github.ref }} on tag push."

      - name: Fail if not synced with dev branch
        run: |
          # This verifies that there is only one file changed between dev and this branch,
          # that the file is our version file, and that only one line has changed.
          # If these criteria are not met, the action fails here and no pr is made.
          [ '1 1 .github/staging-version' = "`git diff --numstat --no-color dev HEAD -- | xargs`" ]
      - name: Push and create pull request
        uses: peter-evans/create-pull-request@v2
        if: ${{ success() }}
        with:
          branch: ${{ github.ref }}-staging-version-update
          branch-suffix: short-commit-hash
          base: dev
          title: 'Release ${{ github.ref }} to staging' 
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
